# Generated by Django 4.1.1 on 2022-09-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialqatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccion',
            name='grupo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
